/** Shared status strings — keep in sync with Prisma schema comments. */

export const BOOKING_TYPE = {
  INSTANT: "INSTANT",
  SCHEDULED: "SCHEDULED"
};

export const BOOKING_STATUS = {
  REQUESTED: "REQUESTED",
  SCHEDULED: "SCHEDULED",
  CONFIRMED: "CONFIRMED",
  ASSIGNED: "ASSIGNED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED"
};

export const RIDE_STATUS = {
  REQUESTED: "REQUESTED",
  ACCEPTED: "ACCEPTED",
  DRIVER_EN_ROUTE: "DRIVER_EN_ROUTE",
  ARRIVED: "ARRIVED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
};

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED"
};

export const MESSAGE_SENDER_ROLE = {
  USER: "USER",
  DRIVER: "DRIVER"
};
