import {
  createContext,
  useContext,
  useState,
  ReactNode,
} from "react";

// Language Context for i18n support
type Language = "ja" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ja: {
    // Header
    profile: "プロフィール",
    rideHistory: "乗車履歴",
    incomeManagement: "収入管理",
    reservation: "予約する",
    logout: "ログアウト",

    // Common
    confirm: "確認",
    cancel: "キャンセル",
    back: "戻る",
    save: "保存",
    next: "次へ",
    submit: "送信",
    skip: "スキップ",
    edit: "編集",
    delete: "削除",
    close: "閉じる",

    // Auth Pages
    welcomeBack: "おかえりなさい",
    loginSubtitle:
      "メールアドレスとパスワードを入力してログインしてください",
    emailAddress: "メールアドレス",
    password: "パスワード",
    rememberMe: "ログイン状態を保持",
    forgotPassword: "パスワードをお忘れですか？",
    login: "ログイン",
    dontHaveAccount: "アカウントをお持ちでないですか？",
    signUp: "新規登録",
    registerAsDriver: "ドライバーとして登録",
    createAccount: "アカウント作成",
    signupSubtitle:
      "情報を入力して新しいアカウントを作成してください",
    fullName: "氏名",
    phoneNumber: "電話番号",
    confirmPassword: "パスワード確認",
    agreeToTerms: "利用規約とプライバシーポリシーに同意します",
    alreadyHaveAccount: "アカウントをお持ちですか？",
    backToLogin: "ログインに戻る",
    becomeDriver: "ドライバーになる",
    driverRegSubtitle: "ドライバー登録情報を入力してください",
    vehicleInfo: "車両情報",
    vehicleType: "車両タイプ",
    selectVehicleType: "車両タイプを選択",
    sedan: "セダン",
    suv: "SUV",
    van: "バン",
    licensePlate: "ナンバープレート",
    vehicleColor: "車両の色",
    vehicleModel: "車両モデル",
    documents: "書類",
    driverLicense: "運転免許証番号",
    licenseExpiry: "免許証有効期限",
    insuranceNumber: "保険証番号",
    languages: "対応言語",
    submitApplication: "申請を送信",
    user: "ユーザー",
    driver: "ドライバー",
    loginToAccount: "アカウントにログインしてください",
    createNewAccount: "新しいアカウントを登録してください",
    firstName: "名",
    lastName: "姓",
    personalInformation: "個人情報",
    driversLicense: "運転免許証",
    licensePhoto: "免許証写真",
    clickToUpload: "クリックしてアップロード",
    vehiclePhoto: "車両写真",
    identificationInformation: "身分証明書情報",
    identificationNumber: "身分証明書番号",
    idCardUpload: "身分証明書アップロード（表・裏）",
    idCardFront: "身分証明書（表）",
    idCardBack: "身分証明書（裏）",
    bankAccountInformation: "銀行口座情報",
    bankName: "銀行名",
    accountNumber: "口座番号",
    accountHolderName: "口座名義",
    languageCertification: "言語証明書",
    languageSkills: "言語能力",
    insuranceInformation: "保険情報",
    insurancePolicyNumber: "保険証券番号",
    insurancePolicy: "保険証券",
    completeRegistration: "登録を完了する",
    selectColor: "色を選択",
    white: "白",
    black: "黒",
    silver: "シルバー",
    blue: "青",
    red: "赤",
    driverNotRegistered: "ドライバー登録がまだですか？",
    register: "登録する",
    enterPassword: "パスワードを入力",
    reEnterPassword: "パスワードを再入力",
    driverRegistration: "ドライバー登録",
    registerAsDriverSubtitle:
      "ドライバーとして登録してください",
    driverSignupHint: "登録ページでアカウント情報・免許・車両・書類を入力します。",
    continueDriverRegistration: "ドライバー登録へ進む",
    accountInformation: "アカウント情報",
    driverAccountSectionNote: "ログイン情報を入力してください。登録後、ドライバー情報を続けて入力します。",
    driverAccountLoggedInNote: "ログイン済みです。アカウント情報を確認し、下のドライバー情報を入力してください（メールは変更できません）。",
    enterBankName: "銀行名を入力",
    enterAccountNumber: "口座番号を入力",
    profileNotFilledYet: "プロフィールをまだ設定していません",
    lookingForDriver: "ドライバーを検索中...",
    lookingForDriverSub: "近くのドライバーに通知しています。しばらくお待ちください。",
    noDriverYet: "まだドライバーが見つかりません",
    canLeaveAndReturn: "ホームに戻っても大丈夫です。ドライバーが見つかるとここから再開できます。",
    driverAssignedNotice: "ドライバーが見つかりました！",
    activeRideWaiting: "ドライバーを探しています",
    activeRideDriverFound: "ドライバーが割り当てられました",
    activeRideAwaitingPayment: "ドライバーが到着しました — お支払いをお願いします",
    driverEndedTrip: "ドライバーが乗車を完了しました。お支払いを確定してください。",
    confirmPayment: "支払いを確定",
    waitingForCustomerPayment: "お客様の支払いを待っています",
    paymentReceived: "お支払いが完了しました",
    continueRide: "続ける",
    cancelRideConfirm: "この予約をキャンセルしますか？",
    cancelActiveBookingPrompt: "進行中の予約があります。キャンセルして新しく予約しますか？",
    home: "ホーム",
    work: "仕事",
    viewAll: "すべて表示",

    // Homepage
    whereToToday: "今日はどこへ？",
    enterDestination: "目的地を入力してください...",
    bookNow: "今すぐ予約",
    scheduleForLater: "後で予約",
    recentDestinations: "最近の目的地",
    quickActions: "クイックアクション",
    bookRide: "乗車予約",
    myReservations: "予約",
    savedAddresses: "保存されたアドレス",
    history: "履歴",

    // Booking
    pickupLocation: "乗車場所を入力",
    destination: "目的地を入力",
    suggestedDestinations: "おすすめの目的地",
    chooseVehicle: "車両を選択",

    // Reservation
    scheduleRide: "乗車予約",
    scheduleSubtitle: "乗車日時を選択してください",
    pickupDate: "乗車日",
    pickupTime: "乗車時刻",
    scheduleNow: "予約する",
    date: "日付",
    time: "時間",
    selectDate: "日付を選択",
    reservationNote:
      "予約は指定時刻の15分前までに確定する必要があります。",
    backToBookNow: "今すぐ予約に戻る",
    important: "ご注意：",
    userCancelled: "利用者がキャンセルしました",
    confirmReservation: "予約を確定",
    reservationConfirmed: "予約が確定しました",
    reservationStatusSubtitle: "ドライバーが承認するまでお待ちください。ステータスは自動更新されます。",
    scheduledPickup: "予約日時",
    reservationWaitingNote: "近くのドライバーに予約が通知されます。承認されるとここに表示されます。",
    reservationStepWaiting: "ドライバー待ち",
    reservationStepAssigned: "ドライバー確定",
    reservationStepEnRoute: "迎車中",
    reservationStepDone: "完了",
    reservationCancelled: "予約はキャンセルされました",
    cancelReservation: "予約をキャンセル",
    cancelReservationConfirm: "この予約をキャンセルしますか？",
    cancelRide: "乗車をキャンセル",
    reservationNotFound: "予約が見つかりません",
    pickupInMinutes: "迎車まで約 {n} 分",
    yourDriver: "担当ドライバー",
    driverWillArriveOnTime: "予約時刻に迎車します",
    driverOnTheWay: "迎車中です",
    trackRide: "乗車を追跡",
    driverStartedPickup: "ドライバーが迎車を開始しました。まもなく到着します。",
    userPickupReminder: "まもなくお迎えです（約 {n} 分後）。ご準備ください。",
    viewInHistory: "予約一覧を見る",
    viewReservationStatus: "予約状況を見る",
    backToHome: "ホームに戻る",
    cancelling: "キャンセル中...",
    cancelFailed: "キャンセルに失敗しました",
    loadFailed: "読み込みに失敗しました",
    saving: "保存中...",
    waitingForDriver: "ドライバー待ち",
    driverAssigned: "ドライバー確定",
    startPickup: "迎車を開始",
    startPickupInMinutes: "{n} 分後に迎車開始できます",
    tooEarlyToStart: "予約時刻の30分前から開始できます",
    pickupStartsSoon: "あと {n} 分で迎車開始できます",
    driverPickupReminder: "{name} さんの迎車時刻まで残り {n} 分です。開始準備をしてください。",
    upcomingReservations: "今後の予約",

    // Vehicles
    economy: "エコノミー",
    comfort: "コンフォート",
    premium: "プレミアム",
    economyDesc: "手頃な価格の乗車",
    comfortDesc: "より快適な乗車",
    premiumDesc: "高級車での乗車",
    capacity: "定員",
    eta: "到着予定",

    // Driver Request
    driverPreferences: "ドライバーの希望",
    languageRequirements: "言語要件",
    japanese: "日本語",
    english: "英語",
    vietnamese: "ベトナム語",
    ridePreferences: "乗車の希望",
    quietRide: "静かな乗車（会話なし）",
    noMusic: "音楽なし",
    airconRequired: "エアコン必須",
    specialRequests: "特別なリクエスト",
    specialRequestsPlaceholder:
      "その他のリクエストがあればご記入ください...",
    confirmBooking: "予約を確定",
    japaneseDriverNote:
      "日本語対応ドライバーは待機時間が長くなる可能性があります（約5-10分）",
    speaksJapanese: "を話せるドライバー",
    speaksEnglish: "を話せるドライバー",
    speaksVietnamese: "を話せるドライバー",
    note: "注意",

    // Payment
    paymentMethod: "支払い方法",
    selectPayment: "支払い方法を選択または追加",
    addNewCard: "新しいカードを追加",
    cardNumber: "カード番号",
    expiry: "有効期限",
    cardName: "カード名義",
    cash: "現金",
    payDriverDirectly: "ドライバーに直接支払い",
    cardInfo: "カード情報",
    cvv: "CVV",
    selectedVehicle: "選択した車両",
    reviewYourBooking: "予約内容をご確認ください",
    estimatedPickup: "予定乗車時刻",
    requestDriver: "ドライバーをリクエスト",

    // Ride
    onRide: "乗車中",
    estimatedArrival: "到着予定",
    minutes: "分",
    headingTo: "へ向かっています",
    supportedLanguages: "対応言語",
    tripDetails: "乗車詳細",
    pickupPoint: "乗車場所",
    destinationPoint: "目的地",
    estimatedFare: "予想料金",
    safetyNote: "乗車情報は家族や友人と共有できます",
    shareTrip: "乗車情報を共有",
    message: "メッセージ",
    call: "通話",
    phone: "電話",
    translate: "翻訳",
    videoCall: "ビデオ通話",
    backToRide: "乗車画面に戻る",
    typeMessage: "メッセージを入力...",
    chatConnected: "リアルタイム接続中",
    tapToStartCall: "タップして通話を開始",
    inCall: "通話中...",
    callDuration: "通話時間",
    callMayBeRecorded: "この通話は録音される場合があります",
    startVideoCall: "ビデオ通話を開始",
    enterTipAmount: "チップ金額を入力してください (VND)",
    translating: "翻訳中...",
    arrivalTime: "到着まで",
    rideComplete: "乗車完了",
    safetyFirst: "安全のため",

    // Rating
    rateYourRide: "乗車はいかがでしたか？",
    rateDriver: "ドライバーを評価してください",
    selectRating: "評価を選択してください",
    veryBad: "非常に悪い",
    bad: "悪い",
    average: "普通",
    good: "良い",
    excellent: "素晴らしい",
    selectCompliments: "良かった点を選択（任意）",
    friendlyDriver: "親切なドライバー",
    cleanVehicle: "清潔な車両",
    safeDriving: "安全運転",
    onTime: "時間厳守",
    greatConversation: "良い会話",
    smoothDriving: "スムーズな運転",
    comment: "コメント",
    commentPlaceholder:
      "ドライバーへのフィードバックをお聞かせください...",
    addTip: "チップを追加（任意）",
    other: "その他",
    submitRating: "評価を送信",
    optional: "任意",

    // Bill
    tripCompleted: "乗車完了",
    tripSummary: "乗車の概要",
    baseFare: "基本料金",
    distanceCharge: "距離料金",
    timeFee: "時間料金",
    toll: "通行料",
    tip: "チップ",
    total: "合計",
    paymentCompleted: "支払い完了",
    downloadReceipt: "領収書をダウンロード",
    tripDate: "乗車日時",
    duration: "乗車時間",
    distance: "距離",
    returnHome: "ホームに戻る",
    nextRide: "次の乗車",
    emailReceipt: "領収書をメール送信",
    receiptEmailSent: "領収書がメールで送信されました",
    thankYouForRiding: "ご利用ありがとうございました",
    totalAmount: "合計金額",
    serviceFee: "サービス料",
    sendReceiptByEmail: "領収書をメールで送信",
    sent: "送信済み",
    send: "送信",
    downloadPDF: "PDFをダウンロード",

    // History
    searchRides: "乗車を検索...",
    filterBy: "フィルター",
    allRides: "すべて",
    completed: "完了",
    cancelled: "キャンセル",
    scheduled: "予約済み",
    downloadAll: "すべてダウンロード",
    rider: "乗客",
    noRidesFound: "乗車履歴が見つかりません",
    searchByDestinationOrDate: "目的地または日付で検索...",
    completedRides: "完了した乗車",
    noCompletedRides: "完了した乗車がありません",
    upcomingRides: "予約済み",
    receipt: "領収書",
    bookAgain: "もう一度予約",
    support: "サポート",
    modifyReservation: "予約を変更",

    // Driver Bill
    goodWork: "お疲れ様でした",
    thisRideEarnings: "この乗車の収入",
    activeHours: "稼働時間",
    dateTime: "日時",
    tollFee: "高速道路料金",
    subtotal: "小計",
    commission: "手数料",
    yourEarnings: "あなたの収入",
    customer: "お客様",
    waitingForRating: "評価待ち...",

    // Driver Ride History
    searchByCustomerOrLocation: "お客様名または場所で検索...",
    today: "今日",
    thisWeek: "今週",
    thisMonth: "今月",
    totalEarnings: "総収入",

    // Profile Pages (User & Driver)
    editPersonalInfo: "個人情報を編集",
    updateNamePhone: "名前、電話番号などを更新",
    updateNameContact: "名前、連絡先などを更新",
    savedPlaces: "保存された場所",
    manageHomeWork: "自宅、職場などを管理",
    managePaymentMethods: "クレジットカードや決済方法を管理",
    paymentSettings: "支払い設定",
    bankAccountPayment: "銀行口座と支払い方法",
    notificationSettings: "通知設定",
    pushEmailSettings: "プッシュ通知とメール設定",
    privacySecurity: "プライバシーとセキュリティ",
    accountSecuritySettings: "アカウントのセキュリティ設定",
    helpSupport: "ヘルプとサポート",
    faqContact: "よくある質問とお問い合わせ",
    membershipPeriod: "会員期間",
    ratingsAndBadges: "評価とバッジ",
    checkCustomerRatings: "お客様からの評価を確認",
    manageVehicleDocuments: "車両の詳細と書類を管理",
    driverExperience: "ドライバー歴",
    earnedBadges: "獲得バッジ",
    fiveStarDriver: "5つ星ドライバー",
    veteran: "ベテラン",
    cleanCar: "クリーンカー",
    multilingualSupport: "多言語対応",

    // Edit Profile
    editProfile: "プロフィール編集",
    profilePhoto: "プロフィール写真",
    changePhoto: "写真を変更",
    imageFormatLimit: "JPG、PNG、最大5MB",
    addressInformation: "住所情報",
    address: "住所",
    city: "市",
    country: "国",
    changePassword: "パスワード変更",
    currentPassword: "現在のパスワード",
    enterCurrentPassword: "現在のパスワードを入力",
    newPassword: "新しいパスワード",
    enterNewPassword: "新しいパスワードを入力",
    reenterPassword: "パスワードを再入力",

    // Edit Profile
    updateProfile: "プロフィールを更新",
    updateSubtitle: "個人情報を更新してください",
    saveChanges: "変更を保存",
    profileUpdated: "プロフィールが更新されました",
    uploadPhoto: "写真をアップロード",

    // Driver Pages
    online: "オンライン",
    offline: "オフライン",
    todayEarnings: "今日の収入",
    weeklyEarnings: "週間収入",
    completedTrips: "完了した乗車",
    averageRating: "平均評価",
    goOnline: "オンラインにする",
    goOffline: "オフラインにする",
    newRideRequest: "新しい乗車リクエスト",
    accept: "承認",
    decline: "辞退",
    pickupIn: "乗車まで",
    passengerInfo: "乗客情報",
    startRide: "乗車開始",
    completeRide: "乗車完了",
    viewDetails: "詳細を見る",
    earnings: "収入",
    weeklyStats: "週間統計",
    monthlyEarnings: "月間収入",
    tripsCompleted: "完了した乗車数",
    hoursOnline: "オンライン時間",
    acceptanceRate: "承認率",
    cancellationRate: "キャンセル率",
    withdraw: "出金",
    vehicleInformation: "車両情報",
    acceptingRides: "乗車依頼を受け付けています",
    notAcceptingRides: "乗車依頼を受け付けていません",
    pickup: "乗車",
    estimatedEarnings: "予想収入",
    acceptRequest: "受け入れる",
    todaysRides: "今日の乗車",
    hours: "時間",
    recentRatings: "最近の評価",
    noRatingsYet: "まだ評価はありません",
    anonymousRider: "匿名のお客様",
    totalRides: "総乗車数",
    viewIncomeManagement: "今週の収入や支払い履歴を確認",
    viewRideHistory: "過去の乗車記録を確認",
    customerInfo: "お客様情報",
    rides: "回の乗車",
    timeRemaining: "承認までの残り時間",
    seconds: "秒",
    estimatedTime: "予想時間",
    acceptRideRequest: "乗車依頼を受け入れる",
    arriving: "到着中",
    arrivedAtPickup: "乗車場所に到着しました",
    waitingForPassenger: "乗客を待っています",
    navigateToPickup: "乗車場所へ移動",
    inProgress: "乗車中",
    navigateToDestination: "目的地へ移動",
    requestedLanguages: "希望言語",
    preferences: "希望",
    expectedEarnings: "予想収入",
    todaysTrips: "今日の乗車数",
    thisWeekEarnings: "今週の収入",
    thisMonthEarnings: "今月の収入",
    withdrawFunds: "出金する",
    earningsBreakdown: "収入の内訳",
    totalDistance: "総走行距離",
    avgEarningsPerTrip: "平均収入/乗車",
    peakHours: "ピーク時間",
    topDestinations: "人気の目的地",

    // Not Found
    pageNotFound: "ページが見つかりません",
    pageNotFoundDesc:
      "探しのページは存在しないか、移動した可能性があります。",

    // Driver Reservation Accept Page
    reservations: "予約リスト",
    viewAndAcceptScheduledRides: "予約された乗車を確認・承認",
    hasReservations: "予約あり",
    noReservationsThisDay: "この日は予約がありません",
    availableRides: "利用可能な予約",
    acceptedRides: "承認済みの予約",
    noAcceptedRides: "承認済みの予約はありません",
    cancelAcceptance: "承認をキャンセル",
  },
  en: {
    // Header
    profile: "Profile",
    rideHistory: "Ride History",
    incomeManagement: "Income Management",
    reservation: "Reservation",
    logout: "Logout",

    // Common
    confirm: "Confirm",
    cancel: "Cancel",
    back: "Back",
    save: "Save",
    next: "Next",
    submit: "Submit",
    skip: "Skip",
    edit: "Edit",
    delete: "Delete",
    close: "Close",

    // Auth Pages
    welcomeBack: "Welcome Back",
    loginSubtitle: "Enter your email and password to login",
    emailAddress: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    login: "Login",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    registerAsDriver: "Register as Driver",
    createAccount: "Create Account",
    signupSubtitle:
      "Fill in the information to create your new account",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    confirmPassword: "Confirm Password",
    agreeToTerms:
      "I agree to the Terms and Conditions and Privacy Policy",
    alreadyHaveAccount: "Already have an account?",
    backToLogin: "Back to Login",
    becomeDriver: "Become a Driver",
    driverRegSubtitle:
      "Fill in your driver registration information",
    vehicleInfo: "Vehicle Information",
    vehicleType: "Vehicle Type",
    selectVehicleType: "Select vehicle type",
    sedan: "Sedan",
    suv: "SUV",
    van: "Van",
    licensePlate: "License Plate",
    vehicleColor: "Vehicle Color",
    vehicleModel: "Vehicle Model",
    documents: "Documents",
    driverLicense: "Driver's License Number",
    licenseExpiry: "License Expiry Date",
    insuranceNumber: "Insurance Number",
    languages: "Languages",
    submitApplication: "Submit Application",
    user: "User",
    driver: "Driver",
    loginToAccount: "Please login to your account",
    createNewAccount: "Please create a new account",
    firstName: "First Name",
    lastName: "Last Name",
    personalInformation: "Personal Information",
    driversLicense: "Driver's License",
    licensePhoto: "License Photo",
    clickToUpload: "Click to upload",
    vehiclePhoto: "Vehicle Photo",
    identificationInformation: "Identification Information",
    identificationNumber: "Identification Number",
    idCardUpload: "Upload ID Card (Front & Back)",
    idCardFront: "ID Card (Front)",
    idCardBack: "ID Card (Back)",
    bankAccountInformation: "Bank Account Information",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    accountHolderName: "Account Holder Name",
    languageCertification: "Language Certification",
    languageSkills: "Language Skills",
    insuranceInformation: "Insurance Information",
    insurancePolicyNumber: "Insurance Policy Number",
    insurancePolicy: "Insurance Policy",
    completeRegistration: "Complete Registration",
    selectColor: "Select color",
    white: "White",
    black: "Black",
    silver: "Silver",
    blue: "Blue",
    red: "Red",
    driverNotRegistered: "Driver registration not yet?",
    register: "Register",
    enterPassword: "Enter password",
    reEnterPassword: "Re-enter password",
    driverRegistration: "Driver Registration",
    driverSignupHint: "Enter account info, license, vehicle details, and documents on the registration page.",
    continueDriverRegistration: "Continue to driver registration",
    accountInformation: "Account Information",
    driverAccountSectionNote: "Enter your login details first. You will complete driver profile information below.",
    driverAccountLoggedInNote: "You are signed in. Review your account info and complete driver details below (email cannot be changed).",
    enterBankName: "Enter bank name",
    enterAccountNumber: "Enter account number",
    profileNotFilledYet: "Profile not set yet",
    lookingForDriver: "Looking for a driver...",
    lookingForDriverSub: "Nearby drivers are being notified. Please wait.",
    noDriverYet: "No driver assigned yet",
    canLeaveAndReturn: "You can go back home. Resume your ride from the banner when a driver is found.",
    driverAssignedNotice: "A driver has accepted your ride!",
    activeRideWaiting: "Looking for a driver",
    activeRideDriverFound: "Driver assigned",
    activeRideAwaitingPayment: "Driver ended trip — please confirm payment",
    driverEndedTrip: "Your driver has ended the trip. Please confirm payment to finish.",
    confirmPayment: "Confirm Payment",
    waitingForCustomerPayment: "Waiting for customer payment",
    paymentReceived: "Payment received",
    continueRide: "Continue ride",
    cancelRideConfirm: "Cancel this booking?",
    cancelActiveBookingPrompt: "You have an active booking. Cancel it and start a new one?",
    registerAsDriverSubtitle: "Please register as a driver",
    home: "Home",
    work: "Work",
    viewAll: "View All",

    // Homepage
    whereToToday: "Where to today?",
    enterDestination: "Enter your destination...",
    bookNow: "Book Now",
    scheduleForLater: "Schedule for Later",
    recentDestinations: "Recent Destinations",
    quickActions: "Quick Actions",
    bookRide: "Book Ride",
    myReservations: "Reservation",
    savedAddresses: "Saved Addresses",
    history: "History",

    // Booking
    pickupLocation: "Enter pickup location",
    destination: "Enter destination",
    suggestedDestinations: "Suggested Destinations",
    chooseVehicle: "Choose Vehicle",

    // Reservation
    scheduleRide: "Schedule a Ride",
    scheduleSubtitle: "Select your pickup date and time",
    pickupDate: "Pickup Date",
    pickupTime: "Pickup Time",
    scheduleNow: "Schedule Now",
    date: "Date",
    time: "Time",
    selectDate: "Select Date",
    reservationNote:
      "Reservations must be confirmed 15 minutes before the specified time.",
    backToBookNow: "Return to Book Now",
    important: "Note:",
    userCancelled: "User cancelled",
    confirmReservation: "Confirm reservation",
    reservationConfirmed: "Reservation confirmed",
    reservationStatusSubtitle: "Waiting for a driver to accept. Status updates automatically.",
    scheduledPickup: "Scheduled pickup",
    reservationWaitingNote: "Nearby drivers are notified. You will see updates here once accepted.",
    reservationStepWaiting: "Waiting for driver",
    reservationStepAssigned: "Driver assigned",
    reservationStepEnRoute: "Driver en route",
    reservationStepDone: "Completed",
    reservationCancelled: "Reservation cancelled",
    cancelReservation: "Cancel reservation",
    cancelReservationConfirm: "Cancel this reservation?",
    cancelRide: "Cancel ride",
    reservationNotFound: "Reservation not found",
    pickupInMinutes: "Pickup in about {n} min",
    yourDriver: "Your driver",
    driverWillArriveOnTime: "Will arrive at scheduled time",
    driverOnTheWay: "Driver is on the way",
    trackRide: "Track ride",
    driverStartedPickup: "Your driver has started heading to pickup.",
    userPickupReminder: "Pickup is coming soon (about {n} minutes). Please get ready.",
    viewInHistory: "View in history",
    viewReservationStatus: "View reservation status",
    backToHome: "Back to home",
    cancelling: "Cancelling...",
    cancelFailed: "Could not cancel",
    loadFailed: "Failed to load",
    saving: "Saving...",
    waitingForDriver: "Waiting for driver",
    driverAssigned: "Driver assigned",
    startPickup: "Start pickup",
    startPickupInMinutes: "Start pickup in {n} min",
    tooEarlyToStart: "You can start within 30 minutes of scheduled time",
    pickupStartsSoon: "Pickup can start in {n} min",
    driverPickupReminder: "{name}'s pickup starts in {n} minutes. Please get ready.",
    upcomingReservations: "Upcoming reservations",

    // Vehicles
    economy: "Economy",
    comfort: "Comfort",
    premium: "Premium",
    economyDesc: "Affordable ride",
    comfortDesc: "More comfortable ride",
    premiumDesc: "Luxury vehicle ride",
    capacity: "Capacity",
    eta: "ETA",

    // Driver Request
    driverPreferences: "Driver Preferences",
    languageRequirements: "Language Requirements",
    japanese: "Japanese",
    english: "English",
    vietnamese: "Vietnamese",
    ridePreferences: "Ride Preferences",
    quietRide: "Quiet ride (no conversation)",
    noMusic: "No music",
    airconRequired: "Air conditioning required",
    specialRequests: "Special Requests",
    specialRequestsPlaceholder:
      "Please write any other requests...",
    confirmBooking: "Confirm Booking",
    japaneseDriverNote:
      "Japanese-speaking drivers may have longer wait times (approximately 5-10 minutes)",
    speaksJapanese: " speaking driver",
    speaksEnglish: " speaking driver",
    speaksVietnamese: " speaking driver",
    note: "Note",

    // Payment
    paymentMethod: "Payment Method",
    selectPayment: "Select or add payment method",
    addNewCard: "Add New Card",
    cardNumber: "Card Number",
    expiry: "Expiry Date",
    cardName: "Cardholder Name",
    cash: "Cash",
    payDriverDirectly: "Pay driver directly",
    cardInfo: "Card Information",
    cvv: "CVV",
    selectedVehicle: "Selected Vehicle",
    reviewYourBooking: "Review your booking details",
    estimatedPickup: "Estimated Pickup",
    requestDriver: "Request Driver",

    // Ride
    onRide: "On Ride",
    estimatedArrival: "Estimated Arrival",
    minutes: "min",
    headingTo: " heading to",
    supportedLanguages: "Supported Languages",
    tripDetails: "Trip Details",
    pickupPoint: "Pickup Location",
    destinationPoint: "Destination",
    estimatedFare: "Estimated Fare",
    safetyNote:
      "You can share your trip information with family and friends",
    shareTrip: "Share Trip",
    message: "Message",
    call: "Call",
    phone: "Phone",
    translate: "Translate",
    videoCall: "Video Call",
    backToRide: "Back to Ride",
    typeMessage: "Type a message...",
    chatConnected: "Live chat connected",
    tapToStartCall: "Tap to start the call",
    inCall: "In call...",
    callDuration: "Call duration",
    callMayBeRecorded: "This call may be recorded",
    startVideoCall: "Start video call",
    enterTipAmount: "Enter tip amount (VND)",
    translating: "Translating...",
    arrivalTime: "Arrival in",
    rideComplete: "Complete Ride",
    safetyFirst: "For safety",

    // Rating
    rateYourRide: "How was your ride?",
    rateDriver: "Please rate your driver",
    selectRating: "Please select a rating",
    veryBad: "Very Bad",
    bad: "Bad",
    average: "Average",
    good: "Good",
    excellent: "Excellent",
    selectCompliments: "Select what you liked (optional)",
    friendlyDriver: "Friendly driver",
    cleanVehicle: "Clean vehicle",
    safeDriving: "Safe driving",
    onTime: "On time",
    greatConversation: "Great conversation",
    smoothDriving: "Smooth driving",
    comment: "Comment",
    commentPlaceholder:
      "Please share your feedback about the driver...",
    addTip: "Add Tip (optional)",
    other: "Other",
    submitRating: "Submit Rating",
    optional: "optional",

    // Bill
    tripCompleted: "Trip Completed",
    tripSummary: "Trip Summary",
    baseFare: "Base Fare",
    distanceCharge: "Distance Charge",
    timeFee: "Time Fee",
    toll: "Toll",
    tip: "Tip",
    total: "Total",
    paymentCompleted: "Payment Completed",
    downloadReceipt: "Download Receipt",
    tripDate: "Trip Date",
    duration: "Duration",
    distance: "Distance",
    returnHome: "Return to Home",
    nextRide: "Next Ride",
    emailReceipt: "Email Receipt",
    receiptEmailSent: "Receipt has been sent to your email",
    thankYouForRiding: "Thank you for riding with us",
    totalAmount: "Total Amount",
    serviceFee: "Service Fee",
    sendReceiptByEmail: "Send Receipt by Email",
    sent: "Sent",
    send: "Send",
    downloadPDF: "Download PDF",

    // History
    searchRides: "Search rides...",
    filterBy: "Filter by",
    allRides: "All",
    completed: "Completed",
    cancelled: "Cancelled",
    scheduled: "Scheduled",
    downloadAll: "Download All",
    rider: "Rider",
    noRidesFound: "No rides found",
    searchByDestinationOrDate:
      "Search by destination or date...",
    completedRides: "Completed rides",
    noCompletedRides: "No completed rides yet",
    upcomingRides: "Upcoming rides",
    receipt: "Receipt",
    bookAgain: "Book again",
    support: "Support",
    modifyReservation: "Modify reservation",

    // Driver Bill
    goodWork: "Good work",
    thisRideEarnings: "Earnings from this ride",
    activeHours: "Active hours",
    dateTime: "Date & Time",
    tollFee: "Toll fee",
    subtotal: "Subtotal",
    commission: "Commission",
    yourEarnings: "Your Earnings",
    customer: "Customer",
    waitingForRating: "Waiting for rating...",

    // Driver Ride History
    searchByCustomerOrLocation:
      "Search by customer or location...",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    totalEarnings: "Total Earnings",

    // Profile Pages (User & Driver)
    editPersonalInfo: "Edit Personal Info",
    updateNamePhone: "Update Name, Phone, etc.",
    updateNameContact: "Update Name, Contact, etc.",
    savedPlaces: "Saved Places",
    manageHomeWork: "Manage Home, Work, etc.",
    managePaymentMethods:
      "Manage Credit Cards & Payment Methods",
    paymentSettings: "Payment Settings",
    bankAccountPayment: "Bank Account & Payment Methods",
    notificationSettings: "Notification Settings",
    pushEmailSettings: "Push Notifications & Email Settings",
    privacySecurity: "Privacy & Security",
    accountSecuritySettings: "Account Security Settings",
    helpSupport: "Help & Support",
    faqContact: "FAQ & Contact",
    membershipPeriod: "Membership Period",
    ratingsAndBadges: "Ratings & Badges",
    checkCustomerRatings: "Check Customer Ratings",
    manageVehicleDocuments:
      "Manage Vehicle Details & Documents",
    driverExperience: "Driver Experience",
    earnedBadges: "Earned Badges",
    fiveStarDriver: "5-Star Driver",
    veteran: "Veteran",
    cleanCar: "Clean Car",
    multilingualSupport: "Multilingual Support",

    // Edit Profile
    editProfile: "Edit Profile",
    profilePhoto: "Profile Photo",
    changePhoto: "Change Photo",
    imageFormatLimit: "JPG, PNG, max 5MB",
    addressInformation: "Address Information",
    address: "Address",
    city: "City",
    country: "Country",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    enterCurrentPassword: "Enter current password",
    newPassword: "New Password",
    enterNewPassword: "Enter new password",
    reenterPassword: "Re-enter password",

    // Edit Profile
    updateProfile: "Update Profile",
    updateSubtitle: "Update your personal information",
    saveChanges: "Save Changes",
    profileUpdated: "Profile has been updated",
    uploadPhoto: "Upload Photo",

    // Driver Pages
    online: "Online",
    offline: "Offline",
    todayEarnings: "Today's Earnings",
    weeklyEarnings: "Weekly Earnings",
    completedTrips: "Completed Trips",
    averageRating: "Average Rating",
    goOnline: "Go Online",
    goOffline: "Go Offline",
    newRideRequest: "New Ride Request",
    accept: "Accept",
    decline: "Decline",
    pickupIn: "Pickup in",
    passengerInfo: "Passenger Information",
    startRide: "Start Ride",
    completeRide: "Complete Ride",
    viewDetails: "View Details",
    earnings: "Earnings",
    weeklyStats: "Weekly Stats",
    monthlyEarnings: "Monthly Earnings",
    tripsCompleted: "Trips Completed",
    hoursOnline: "Hours Online",
    acceptanceRate: "Acceptance Rate",
    cancellationRate: "Cancellation Rate",
    withdraw: "Withdraw",
    vehicleInformation: "Vehicle Information",
    acceptingRides: "Accepting Ride Requests",
    notAcceptingRides: "Not Accepting Ride Requests",
    pickup: "Pickup",
    estimatedEarnings: "Estimated Earnings",
    acceptRequest: "Accept Request",
    todaysRides: "Today's Rides",
    hours: "Hours",
    recentRatings: "Recent Ratings",
    noRatingsYet: "No ratings yet",
    anonymousRider: "Anonymous rider",
    totalRides: "Total Rides",
    viewIncomeManagement: "View Income Management",
    viewRideHistory: "View Ride History",
    customerInfo: "Customer Information",
    rides: "Rides",
    timeRemaining: "Time Remaining",
    seconds: "Seconds",
    estimatedTime: "Estimated Time",
    acceptRideRequest: "Accept Ride Request",
    arriving: "Arriving",
    arrivedAtPickup: "Arrived at Pickup",
    waitingForPassenger: "Waiting for Passenger",
    navigateToPickup: "Navigate to Pickup",
    inProgress: "In Progress",
    navigateToDestination: "Navigate to Destination",
    requestedLanguages: "Requested Languages",
    preferences: "Preferences",
    expectedEarnings: "Expected Earnings",
    todaysTrips: "Today's Trips",
    thisWeekEarnings: "This Week's Earnings",
    thisMonthEarnings: "This Month's Earnings",
    withdrawFunds: "Withdraw Funds",
    earningsBreakdown: "Earnings Breakdown",
    totalDistance: "Total Distance",
    avgEarningsPerTrip: "Average Earnings per Trip",
    peakHours: "Peak Hours",
    topDestinations: "Top Destinations",

    // Not Found
    pageNotFound: "Page Not Found",
    pageNotFoundDesc:
      "The page you're looking for doesn't exist or has been moved.",

    // Driver Reservation Accept Page
    reservations: "Reservation List",
    viewAndAcceptScheduledRides: "View and Accept Scheduled Rides",
    hasReservations: "Has Reservations",
    noReservationsThisDay: "No Reservations This Day",
    availableRides: "Available Reservations",
    acceptedRides: "Accepted Reservations",
    noAcceptedRides: "No Accepted Reservations",
    cancelAcceptance: "Cancel Acceptance",
  },
};

const LanguageContext = createContext<
  LanguageContextType | undefined
>(undefined);

const fallbackLanguageContext: LanguageContextType = {
  language: "en",
  setLanguage: () => {
    /* noop fallback */
  },
  t: (key: string) => key
};

// Language Provider Component - Provides translation functionality to the app
export function LanguageProvider({
  children,
}: {
  children: ReactNode;
}) {
  const [language, setLanguage] = useState<Language>("ja");

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof typeof translations.ja
      ] || key
    );
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    return fallbackLanguageContext;
  }
  return context;
}

// Export type for external use
export type { Language, LanguageContextType };